config/routes.rb
Listrhino::Application.routes.draw do
  
  root :to => "home#index"

  resources :feeds
  resources :users
  resources :sessions

  resources :articles do
    member do
      get :rate
      get :next
      get :previous
    end
  end

  match "/home/alt_index" => "home#alt_index"
  match "news_feed" => "home#news_feed"
  match "/home/ofeedia" => "home#ofeedia"
  post "mailing_list" => "home#sign_up"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

end

app/models/article.rb
class Article < ActiveRecord::Base
  def published_at
    created_at.strftime("%b %d, %Y, %l:%M%p %Z") #replace with published at date later
  end

  def feature_content
    article_content[0,200]
  end

  def read_more_content
    article_content[200, article_content.length]
  end

  def article_content
    @content ||= self.content
  end

  def next
    articles = Article.where("id > ?", self.id)
    if articles.empty?
      Article.order("id ASC").first
    else
      articles.first
    end
  end

  def previous
    articles = Article.where("id < ?", self.id)
    if articles.empty?
      Article.order("id DESC").first
    else
      articles.last
    end
  end

  def self.create_articles
    rss = SimpleRSS.parse open('http://news.yahoo.com/rss/personal-finance')
    rss.items.each do |item|
      link_url = item.link
      doc = Pismo::Document.new(link_url)
      Article.create(title: doc.title, content: doc.body, written_date: doc.datetime, source: link_url)
    end
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/feed.rb
class Feed < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create

  has_many :feeds

  serialize :likes
  serialize :dislikes
  serialize :keeps

  def rated?(article)
    ratings = []
    ratings << self.likes << self.dislikes << self.keeps
    if ratings.flatten.include?(article.id)
      true
    else
      false
    end
  end

  def rating(article)
    case
      when self.likes.include?(article.id)
        "You like this article!"
      when self.dislikes.include?(article.id)
        "You dislike this article!"
      when self.keeps.include?(article.id)
        "You kept this article!"
    end
  end

  def like(article)
    self.likes << article.id unless self.likes.include? article.id
  end

  def dislike(article)
    self.dislikes << article.id unless self.dislikes.include? article.id
  end

  def keep(article)
    self.keeps << article.id unless self.keeps.include? article.id
  end

  def likes
    if self[:likes]
      self[:likes]
    else
      self[:likes] = []
      self.save!
      self[:likes]
    end
  end

  def dislikes
    if self[:dislikes]
      self[:dislikes]
    else
      self[:dislikes] = []
      self.save!
      self[:dislikes]
    end
  end

  def keeps
    if self[:keeps]
      self[:keeps]
    else
      self[:keeps] = []
      self.save!
      self[:keeps]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  def rate
    user = User.find_by_id(current_user.id)
    article = Article.find_by_id(params[:id])
    case params[:rate]
      when "good"
        user.like(article)
      when "keep"
        user.keep(article)
      when "kick"
        user.dislike(article)
    end
    user.save!
    redirect_to news_feed_path(:article_id => article)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @email = Email.new
    render :layout => 'finport'
  end

  def alt_index
  end

  def news_feed
    if params[:article_id]
      @article = Article.find_by_id(params[:article_id])
    else
      @article = Article.first
    end

    redirect_to root_url unless current_user
  end

  def ofeedia
  end

  def sign_up
    @email = Email.new(params[:email])

    if @email.save
      flash[:notice] = "Successfully subscribed to the mailing list!"
    else
      flash[:notice] = "Sorry, there was an error with your e-mail address."
    end

    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to news_feed_path, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to news_feed_path, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/_feature.html.haml
#feature.hero-unit
  .row
    .pull-left
      = link_to "« Back", news_feed_path(:article_id => @article.previous)
    .pull-right
      = link_to "Next »", news_feed_path(:article_id => @article.next)
  %h2.headline= @article.title
  .source
    %a{:href => "#"}= @article.source
  .mute
    = @article.published_at
  %br/
  .row
    %ul.thumbnails{:style => "margin-left: 0; padding-left: 0;"}
      %li.span3
        %a.thumbnail{:href => "#"}
          %img{:alt => "", :src => "http://placehold.it/260x180"}
  .row
    .span3
      - if current_user.rated?(@article)
        = current_user.rating(@article)
      - else
        %ul
          %li
            = link_to rate_article_path(@article, :rate => :good), :class => "btn btn-success" do
              %i.icon-arrow-up
              good
          %li
            = link_to rate_article_path(@article, :rate => :keep), :class => "btn btn-info" do
              %i.icon-arrow-left
              keep
          %li
            = link_to rate_article_path(@article, :rate => :kick), :class => "btn btn-danger" do
              %i.icon-arrow-left
              kick
  %br/
  .feature-text
    %span
      = @article.feature_content
    %br/
    %a.read-more-link{:href => "#/more"} read more »
  %br/
  .read-more-text
    %span
      = @article.read_more_content
    %br/
    %a.read-less-link{:href => "#/less"} read less »
  %br/
  %ul.feedback
    %li
      %a.feedback-ok{:href => "#/ok"}
        %i.icon-ok
    %li
      %a.feedback-remove{:href => "#/remove"}
        %i.icon-remove
    %li
      %a.feedback-comments{:href => "#/comments"}
        %i.icon-comment
    %li
      %a.feedback-tags{:href => "#/tags"}
        %i.icon-tags
    %li
      %a.feedback-save{:href => "#/save"}
        %i.icon-check
    %li
      %a.feedback-share{:href => "#/share"}
        %i.icon-share

app/views/home/alt_index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>FinPort beta</title>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="js/timeago.js"></script>    
    <script type="text/javascript">
    google.load("feeds", "1");

    function showRSS(str) {
      var feed = new google.feeds.Feed("http://finance.yahoo.com/rss/headline?s="+str);
      feed.setNumEntries(10);


      $("table").filter(".article").remove();
      $("#tags li").removeClass("active");
      $("#tags").prepend($("<li></li>").append( $('<a></a>').attr('href','#')
                                                            .text(str))
                                       .addClass("active"));

      if ($("#rssOutput ul").length == 0) {
          $("#rssOutput").prepend( $("<ul></ul>").addClass( "nav nav-pills" ).append( $("<li></li>").addClass("active")
    	                                                                                            .append( $("<a></a>").attr("href","#/recent")
	                                                                                                                 .text("recent")))
                                                                	     .append( $("<li></li>").append( $("<a></a>").attr("href","#/archived")
	                                                                                                                 .text("archived"))));
      }    

        feed.load(function(result) {
        if (!result.error) {

          for (var i = 0; i < result.feed.entries.length; i++) {
            var entry = result.feed.entries[i];

            var table = $("<table></table>").addClass("article table table-bordered");
            var body = $("<tbody></tbody>");                              
            var row = $("<tr></tr>");
            var col = $("<td></td>");

            var article = $("<div></div>").addClass("article-container");
            var title = $("<div></div>").addClass("title");
            title.text(entry.title)
                 .css('font-weight','bold');
            article.append(title);

            var pub = $("<div></div>").addClass("mute");
            pub.append($("<small></small>").text( jQuery.timeago( entry.publishedDate ) ) );
            article.append(pub);
                              
            var snip = $("<div></div>").addClass("snip");
            snip.append($("<small></small>").text(entry.contentSnippet));
            article.append(snip);

            var link = $("<div></div>").addClass("link");
            link.append( $("<a></a>").attr('href',entry.link)
                                     .html('read more &raquo;') );
            article.append(link);

            var feedback = $("<ul></ul>").addClass("feedback");                  
            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-ok icon-white"))
			                                        .attr('href',"#/ok")
                                                                .addClass("feedback-ok")));
            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-remove icon-white"))
      			                                        .attr('href',"#/remove")
                                                                .addClass("feedback-remove")));
            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-comments icon-white"))
			                                        .attr('href',"#/comments")			      
                                                                .addClass("feedback-comments")));
                              
            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-tags icon-white"))
			                                        .attr('href',"#/tags")			      			      
                                                                .addClass("feedback-tags")));

            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-check icon-white"))
			                                        .attr('href',"#/share")			      			      			      
                                                                .addClass("feedback-save")));
	      
            feedback.append( $("<li></li>").append( $("<a></a>").html( $("<i></i>").addClass("icon-share icon-white"))
			                                        .attr('href',"#/share")			      			      			      
                                                                .addClass("feedback-share")));

            article.append(feedback);
                              
            col.append(article);                  
            row.append(col);
            body.append(row)                              
            table.append(body);
            $("#rssOutput").append(table);
          }
        }
      });
    }
    </script>    
    <link href="css/bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="css/fontawesome/css/font-awesome.css" rel="stylesheet">
    <link href="css/custom.css" rel="stylesheet">        
    <style type="text/css">
      body {
      padding-top: 60px;
      padding-bottom: 40px;
      }
    </style>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <span class="icon-bar"></span>
          <a class="brand" href="#">FinPort</a>
          <ul class="nav">
            <li class="active"><a href="#/home"><i class="icon-home icon-large icon-white"></i> Home</a></li>
            <li><a class="" href="#/trends"><i class="icon-bar-chart icon-large icon-white"></i> Trends</a>            
            <li><a class="" href="#/help"><i class="icon-info-sign icon-large icon-white"></i> Help</a>              
          </ul>
          <div class="pull-right">
            <ul class="nav">
              <li><a href="#/logout">Logout <i class="icon-signout icon-large icon-white"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>  <!-- end navbar -->

    <div class="container">
      
      <div class="row">
        <div class="span3">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <td>

		  <div class="input-prepend">
		    <span class="add-on"><h4><i class="icon-user icon-large"></i></h4></span>
		    <input class="span2" id="prependedInput" size="16" type="text" placeholder="your username">
		  </div>
<!--		  
                </td>
              </tr>
              <tr>
                <td> -->
                  <h4>Your Stats</h4>
                  <div><i class="icon-eye-open"></i> read</div>
                  <div><i class="icon-thumbs-up"></i> liked</div>
                  <div><i class="icon-comments"></i> comments</div>
                </td>
              </tr>  
              <tr>
                <td>
                  <h4>Connections</h4>
                  <div><i class="icon-facebook-sign icon-large"></i><a href="#/facebook"> Facebook</a></div>
                  <div><i class="icon-twitter-sign icon-large"></i><a href="#/twitter"> Twitter</a></div>
                  <div><i class="icon-linkedin-sign icon-large"></i><a href="#/linkedin"> LinkedIn</a></div>
                </td>
              </tr>
              <tr>
                <td>
		  <p class="help-block"> Enter a Stock Ticker, Company, or Industry</p>

		  <div class="input-prepend">
                    <form class="form-search" onsubmit="showRSS(this.term.value); return false;">		  		      
		      <span class="add-on"><h4><i class="icon-search icon-large"></i></h4></span>
		      <input class="span2" name="term" id="prependedSearch" size="16" type="text" placeholder="search">

		    </form>
		  </div>		  
		  
		  <!--
                  <form class="form-search" onsubmit="showRSS(this.term.value); return false;">                    
                    <input type="text" name="term" class="input-small search-query">
                    <button type="submit" class="btn-mini"><i class="icon-search"></i> Search</button>
                  </form>
		  -->

                </td>
              </tr>
              <tr>
                <td>
                  <h4>Feeds / Tags</h4>
                  <!--<div id="tags"></div>-->
		  <!--
                  <ul id="tags" class="nav nav-pills nav-stacked"></ul>
		  -->
                  <ul id="tags" class="nav nav-pills"></ul>		  
                  <a href="#/all-feeds">view all</a>
                </td>
              </tr>
            </tbody>
          </table>

          <table class="table table-bordered">
            <tbody>
              <tr>
                <td>
                  <!--footer-->
	          <h4>FinPort</h4>
                  <div class="module site-footer">
                    <ul class="clearfix">
                      <li class="copyright"><h5>&copy; 2012 FinPort</h5></li>
                      <li><a href="#/about">About</a></li>
                      <li><a href="#/support">Help</a></li>
                      <li><a href="#/tos">Terms</a></li>
                      <li><a href="#/privacy">Privacy</a></li>
                      <li><a href="#/blog">Blog</a></li>
                      <li><a href="#/media">Media</a></li>
                      <li><a href="#/advertisers">Advertisers</a></li>
                      <li><a href="#/jobs">Jobs</a></li>
                    </ul>
                  </div>
                  <!-- end article-->
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="span6">
          <div id="feature" class="hero-unit">
            <h2 class="feature-headline">Featured Article Headline Here</h2>
            <div class="feature-source">
              <a href="#" >source.com</a>
            </div>
            <div class="mute">
              By Edit Staff | Mar. 11, 2012, 7:00pm PT
            </div>
            <div class="feature-text">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nunc nunc, congue et euismod a, feugiat et magna. Cras laoreet tortor nec dolor euismod in aliquam risus gravida. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas ipsum urna, feugiat quis varius eu, aliquet in tortor.
	      <a href="#/more">read more &raquo;</a>
            </div>
	    
	    <ul class="share">
              <li><a href="#" ><i class="icon-check"></i> save</a></li>
              <li><a href="#" ><i class="icon-share"></i> share</a></li>	      
	      <li><a href="#" ><i class="icon-fire"></i> trending in [tag1], [tag2] and [tag3]</a></li>
            </ul>
	    
          </div> <!-- end hero-unit -->
	  <!--
          <ul class="nav nav-pills">            
            <li class="active"><a href="#home">recent</a></li>
            <li><a href="#/archives">archived</a></li>
            <li><a href="#/refresh">refresh</a></li>
          </ul>
	  -->
          <div id="rssOutput"></div>
        </div> <!-- end span6 -->
        <div class="span3">
	  
          <table class="table table-bordered">
            <tbody>
	      <tr>
                <td>
                  <div class="engine">
		    <h3><i class="icon-cogs icon-large"></i>  FinPort A.I.</h3>		    
                  </div>
                </td>
	      </tr>
	      <tr>
                <td>
                  <div class="engine">		  
                    <h4>You Might Like</h4>
		    <h5>&laquo; Suggested Article 1 &raquo;</h5>
		  </div>
                </td>
	      </tr>  
            </tbody>
          </table>
	  
        </div> <!-- end span3 -->
      </div>  <!-- end row -->
      
    </div> <!--end container-->

  </body>
</html>
    

app/views/home/index.html.haml
.container
  .hero-unit
    #header.row
      .span16
        %h2 FinPort uses machine learning to curate financial news that’s personally relevant to you, to help you make smarter investment decisions.
        %p.lead FinPort helps you sift through the deluge that is financial news. We show you the most important, relevant news, so you don't have to go searching for it.
  .row
    .span4.offset4
      %h3 Join our mailing list to get an invite to the FinPort Beta release
      = form_for @email, :url => "mailing_list" do |f|
        = f.email_field :address, :class => "span3", :placeholder => "email address"
        = f.submit "Sign Up for Finport Beta »", :class => "btn btn-primary btn-large"
  %br/
.container
  %hr/
  .row
    .span10
      %a{:href => "#/about"} About
      %a{:href => "mailto:hello@finport.com"} Contact
      %a{:href => "http://twitter.com/finport"} @finport
    .span2
      .pull-right
        %a{:href => "http://mixpanel.com/f/partner"}
          %img{:alt => "Real Time Web Analytics", :src => "https://mixpanel.com/site_media/images/partner/badge_light.png"}/

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FinPort beta</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "refresh" %>
  <%= javascript_include_tag "timeago" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <span class="icon-bar"></span>
        <a class="brand" href="#">FinPort</a>
        <ul class="nav">
          <li class="active">
            <%= link_to current_user ? news_feed_path : root_url do %>
              <i class="icon-home icon-white"></i> Home
            <% end %>
          </li>
          <li><a class="" href="#/trends"><i class="icon-bar-chart icon-white"></i> Trends</a>            
          <li><a class="" href="#/help"><i class="icon-info-sign icon-white"></i> Help</a>              
        </ul>
        <div class="pull-right">
          <ul class="nav">
            <% if !current_user %>
              <li><%= link_to "Sign-up", signup_path %></li>
              <li><%= link_to "Login", login_path %></li>
            <% else %>
              <li><%= link_to "Logout", logout_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>  <!-- end navbar -->

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
  </div>

  <%= yield %>

</body>
</html>

app/views/layouts/finport.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>FinPort Beta</title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <style type="text/css">
      body {
      padding-top: 60px;
      padding-bottom: 40px;
      }
    </style>
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-30176631-1']);
      _gaq.push(['_trackPageview']);
      (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>    
  </head>
  <body class="<%= params[:controller] %>">    
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">FinPort</a>
          <ul class="nav">
            <li class="active">
            <%= link_to root_url do %>
            <i class="icon-home icon-white"></i> Home
            <% end %>
            </li>
          </ul>
          <div class="pull-right">
            <ul class="nav">
              <li><%= link_to "Login", login_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>

    <%= yield %>
    
    <!--
    <div rel="0FPVYWTV" class="lrdiscoverwidget" data-logo="on" data-background="on" data-share-url="ofeedia.com" data-css="">
    </div>
    <script type="text/javascript" src="http://launchrock-ignition.s3.amazonaws.com/ignition.1.1.js">
    </script>
    -->
  </body>
</html>

app/views/users/new.html.haml
.container
  .span5.offset4
    %h1 Sign Up
    = form_for @user do |f|
      - if @user.errors.any?
        .error_messages
          %h2 Form is invalid
          %ul
            - for message in @user.errors.full_messages
              %li= message
      .field
        = f.label :email
        = f.text_field :email
      .field
        = f.label :password
        = f.password_field :password
      .field
        = f.label :password_confirmation
        = f.password_field :password_confirmation
      .actions
        = f.submit "Sign up", :class => "btn-primary btn-large"